const express = require('express')
const imgrouter = require('./router/image.router')
const app = express()
const cors = require("cors")
require("./config/db")
app.use(cors())
app.use(express.json())
// app.use(express.urlencoded({extended:false}))
app.use("/uploads",express.static("upload"))
app.use(imgrouter)
app.listen(5000, ()=>console.log('server'))