const express = require('express')
const categoryrouter = require('./router/category.router')
const productrouter = require('./router/product.router')
const app =express()
require('./config/db')
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use('/product',productrouter)
app.use('/category',categoryrouter)

app.listen(5000,()=>console.log('server is running'))