const express = require('express')
const router = require('./router/category.router')
const app =express()
require('./config/db')
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use('/',router)
app.listen(5000,()=>console.log('server is running'))