const express = require('express')
const categoryrouter = require('./router/category.router')
const productrouter = require('./router/product.router')
const app =express()
const cors =require('cors')
require('./config/db')
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use(cors())
app.use(productrouter)
app.use(categoryrouter)

app.listen(5000,()=>console.log('server is running'))