const express = require('express')
const router = require('./router/jwt.router')
const app = express()
app.use(express.json())
app.use(router)
app.listen("5000",()=>console.log("server is running 5000"))